[tool.poetry]
name = "pythonproject5"
version = "0.1.0"
description = ""
authors = ["Fox-IK <ilya-kim-1999@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
